%% we need to write a function to initialize the vehicle
function State = Vehicle_Initialize(Id,...
                                    x, y,...
                                    v, theta,...
                                    omega, alpha,...
                                    lane_change_duration,...
                                    lane_change_timer,...
                                    lane_change_direction,...
                                    lambda)
           State.Id = Id;
           State.x = x;
           State.y = y;
           State.v = v;
           State.theta = theta;
           State.omega = omega;
           State.alpha = alpha;
           State.lane_change_duration = lane_change_duration;
           State.lane_change_timer = lane_change_timer;
           State.lane_change_direction ...
               = lane_change_direction;
           State.lambda = lambda;
end